#!/bin/bash

echo "Update package..."
apt update

echo "Membuat service monitoring-wifi..."

cat <<EOF > /etc/systemd/system/monitoring-wifi.service
[Unit]
Description=RizkiNet NMS Monitoring Service
After=network.target

[Service]
User=root
WorkingDirectory=/root/monitoring-wifi
Environment=PATH=/root/monitoring-wifi/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

ExecStart=/root/monitoring-wifi/venv/bin/gunicorn --workers 1 --threads 4 --bind 0.0.0.0:5002 --timeout 120 app:app

Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

echo "Reload systemd..."
systemctl daemon-reload

echo "Enable service..."
systemctl enable monitoring-wifi

echo "Start service..."
systemctl start monitoring-wifi

echo "Restart service..."
systemctl restart monitoring-wifi

echo "Status service..."
systemctl status monitoring-wifi
